ref:
  genome: "/home/daria/Documents/Project2/GRCh37.primary_assembly.genome.fa"

bam_file: "/home/daria/Documents/Project2/SoCHR22_hg19.bam"

filtering:
    snps:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"


gatk:
    HaplotypeCaller: "/home/daria/Documents/Project2/gatk-4.1.0.0"