ref: '/mnt/IMBG-NGS-Analysys/StudentWork/reference/hs37d5.fa'

gatk: '/home/daria/gatk-4.1.0.0/gatk'

dbsnp: '/mnt/IMBG-NGS-Analysys/StudentWork/reference/00-All.vcf'

bed_file: '/mnt/IMBG-NGS-Analysys/StudentWork/reference/Agilent_ExomeV6_S07604514_Padded.picard.interval_list'
